import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import Particle from "../Particle";

function PrivacyPolicy() {
  return (
    <Container fluid className="about-section">
      <Particle />
      <Container>
        <Row style={{ justifyContent: "center", padding: "10px" }}>
          <Col md={10} style={{ paddingBottom: "50px" }}>
            <h1 style={{ fontSize: "2.1em", paddingBottom: "20px" }} className="project-heading">
              Privacy <strong className="purple">Policy</strong>
            </h1>
            <div style={{ textAlign: "left", color: "white", padding: "20px", backgroundColor: "rgba(0,0,0,0.5)", borderRadius: "10px", marginTop: "20px", lineHeight: "1.6" }}>
              <h2 style={{ color: "#c770f0" }}>1. Introduction</h2>
              <p>Welcome to the Sensa Smart application. We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application. This is particularly important for your trust and for our compliance with Apple App Store guidelines.</p>

              <h2 style={{ color: "#c770f0" }}>2. Information We Collect</h2>
              <p>We may collect information about you in a variety of ways. The information we may collect via the Application includes:</p>
              <ul>
                <li><strong>Personal Data:</strong> Demographics and other personally identifiable information (such as your name and email address) that you voluntarily give to us when choosing to participate in various activities related to the Application.</li>
                <li><strong>Device Data:</strong> We may collect device-specific information (such as your hardware model, operating system version, unique device identifiers, and mobile network information) to ensure the App functions correctly with your smart home setup.</li>
                <li><strong>Location Data:</strong> We may request access or permission to and track location-based information from your mobile device, either continuously or while you are using our Application, to provide location-based services like geofencing and home automation based on presence.</li>
                <li><strong>Smart Home Device Data:</strong> Data generated by your connected smart home devices (e.g., temperature readings, switch states, sensor logs) to provide the core functionality of the App.</li>
                <li><strong>Camera and Microphone:</strong> If your smart home setup includes cameras or intercoms, we may request access to your device's camera and microphone to enable features like live streaming and two-way audio.</li>
              </ul>

              <h2 style={{ color: "#c770f0" }}>3. How We Use Your Information</h2>
              <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Application to:</p>
              <ul>
                <li>Operate, manage, and maintain your smart home devices and systems.</li>
                <li>Create and manage your account securely.</li>
                <li>Improve our Application and user experience by analyzing usage trends.</li>
                <li>Respond to customer service requests and provide technical support.</li>
                <li>Send you push notifications regarding your home status (e.g., security alerts, automation completions).</li>
              </ul>

              <h2 style={{ color: "#c770f0" }}>4. Disclosure of Your Information</h2>
              <p>We prioritize your privacy and do not share, sell, rent, or trade any of your personal information with third parties for their promotional purposes. We may disclose your information in the following limited situations:</p>
              <ul>
                <li><strong>By Law or to Protect Rights:</strong> If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others.</li>
                <li><strong>Third-Party Service Providers:</strong> We may share your information with third parties that perform services for us or on our behalf, such as cloud hosting, data analysis, email delivery, hosting services, customer service, and marketing assistance.</li>
              </ul>

              <h2 style={{ color: "#c770f0" }}>5. Security of Your Information</h2>
              <p>We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.</p>

              <h2 style={{ color: "#c770f0" }}>6. Data Retention</h2>
              <p>We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.</p>

              <h2 style={{ color: "#c770f0" }}>7. Contact Us</h2>
              <p>If you have questions or comments about this Privacy Policy, please contact us at: <strong>vulewenlian94@gmail.com</strong></p>
            </div>
          </Col>
        </Row>
      </Container>
    </Container>
  );
}

export default PrivacyPolicy;
